export type Colors_DS = {
  NEUTRAL_BG_MAIN: string;

  NEUTRAL_BORDER_WEAK: string;
  NEUTRAL_BORDER_HIGHLIGHT: string;

  NEUTRAL_TEXT_STRONG: string;
  NEUTRAL_TEXT_WEAK: string;
  NEUTRAL_TEXT_LIGHT: string;

  NEUTRAL_GENERAL_WHITE: string;
  NEUTRAL_GENERAL_BLACK: string;
  NEUTRAL_GENERAL_BLUE: string;
};

export const lightTheme_DS: Colors_DS = {
  NEUTRAL_BG_MAIN: '#FFFFFF',

  NEUTRAL_BORDER_WEAK: '#FFFFFF',
  NEUTRAL_BORDER_HIGHLIGHT: '#00C1C7',

  NEUTRAL_TEXT_STRONG: '#1F2224',
  NEUTRAL_TEXT_WEAK: '#808D9A',
  NEUTRAL_TEXT_LIGHT: '#E2E2E2',

  NEUTRAL_GENERAL_WHITE: '#FFFFFF',
  NEUTRAL_GENERAL_BLACK: '#000000',
  NEUTRAL_GENERAL_BLUE: '#19224A'
};
